### PR TITLE
Feat/websocket update value

### PR DESCRIPTION
**Pull request by tabrindle**
Instantaneous update of device state, even when updated from another place, for example the webapp, app, or physical switches. This is using the websocket API that leviton uses internally. 

Screen Recording 2021-02-23 at 1 53 55 PM

### CODE REVIEW

**Comment by tabrindle** [comment]
@dtesenair Care to take a look? You're the only other one that's done any work with this plugin 😬

**Comment by Dan203** [comment]
> @dtesenair Care to take a look? You're the only other one that's done any work with this plugin 😬

I'm not super familiar with homekit. Is there a way to install a plugin that's not pushed to npm? If so I'm willing to try it out.

**Comment by jonathanweber** [comment]
I installed this branch because I was having an issue with a HomeKit automation based on the state of one of my Leviton devices that wasn’t running in a timely fashion. The good news is, this branch is working fine for me, and I see the status of devices update as soon as I launch the Home app even when the updates were made elsewhere (like in the Leviton app). 

But... my automations still don’t run in the background — they’ll happen immediately when I open the Home app and the value updates. So I am not quite sure if that’s an issue related to this plugin or to HomeKit more generally.

**Comment by Dan203** [comment]
FYI I just finally updated to this new build and it works great. Thank you for updating this it really does make automations easier having everything in HomeKit.

**Pull request merged**
