### PR TITLE
Fix issues with devices not fetching

### PR DESCRIPTION
**Pull request by pbush25**
Update fetch method for iotSwitches to try to use the latest leviton API method of getting the user's residenceID.

See https://github.com/tabrindle/homebridge-leviton/issues/6#issuecomment-1128263800 for details.

### CODE REVIEW

**Comment by pbush25** [comment]
Additional proof this now works by running it locally

```
[5/17/2022, 12:46:55 AM] [LevitonDecoraSmart] No devices found for primary residence id. Trying residence v2
[5/17/2022, 12:46:55 AM] [LevitonDecoraSmart] addAccessory Living Room Fan
[5/17/2022, 12:46:55 AM] [LevitonDecoraSmart] setupService Living Room Fan
[5/17/2022, 12:46:55 AM] [LevitonDecoraSmart] Device Model: DW4SF
[5/17/2022, 12:46:55 AM] [LevitonDecoraSmart] Setting up device as Fan: Living Room Fan
[5/17/2022, 12:46:55 AM] [LevitonDecoraSmart] getStatus Living Room Fan
[5/17/2022, 12:46:55 AM] [LevitonDecoraSmart] Finished adding accessory Living Room Fan
[5/17/2022, 12:46:56 AM] [LevitonDecoraSmart] Socket connection opened Event { type: 'open' }
[5/17/2022, 12:47:06 AM] [LevitonDecoraSmart] onGetRotationSpeed Living Room Fan 50%
[5/17/2022, 12:47:06 AM] [LevitonDecoraSmart] onGetPower Living Room Fan ON
[5/17/2022, 12:47:06 AM] [LevitonDecoraSmart] onGetPower Living Room Fan ON
[5/17/2022, 12:47:06 AM] [LevitonDecoraSmart] onGetRotationSpeed Living Room Fan 50%
[5/17/2022, 12:47:09 AM] [LevitonDecoraSmart] onGetPower Living Room Fan ON
[5/17/2022, 12:47:09 AM] [LevitonDecoraSmart] onGetRotationSpeed Living Room Fan 50%
```

image

**Comment by tabrindle** [comment]
Nicely done! I think what you gave me in the in issue was probably enough to go on, but this is even better! To be honest, I dont understand why the API was designed in this way, but as long as this works for you and does not cause regressions for me, I'll merge and publish it.

**Comment by pbush25** [comment]
Awesome! Looking forward to the next release.

**Comment by pbush25** [comment]
hey @tabrindle unfortunately it looks like you may have had a bad merge when you merged in my PR and the additional logging PR. 

Got this error: `[17/05/2022, 11:02:08] [LevitonDecoraSmart] Error subscribing devices to websocket updates: residenceObjectID is not defined` and in the code I see that `index.js:94` doesn't include the definition for `residenceObjectID`

```
      var { primaryResidenceId: residenceID } = await Leviton.getResidentialAccounts({
```
where it should be 
```
var { primaryResidenceId: residenceID, id: residenceObjectID } = await Leviton.getResidentialAccounts
```

**Comment by pbush25** [comment]
I went ahead and created a new PR: https://github.com/tabrindle/homebridge-leviton/pull/28

**Pull request merged**
