### PR TITLE
Adds `D26HD` second-gen 600W dimmer

### LINKED ISSUE #13: Request to add new dimmer model D26HD to index.js
Request to add the 2nd generation of the 600W dimmer `D26HD`. It appears to show up as a simple switch instead of a dimmer switch:

IMG_45FC2276DCBA-1

I'm assuming it should be as easy as appending below [this case](https://github.com/tabrindle/homebridge-leviton/blob/f03b3dce391a8549c67307934845cf4fe742a5d7/index.js#L258) :)

### PR DESCRIPTION
**Pull request by brandonb927**
Resolves #13 

This PR adds the 600W 2nd generation dimmer switch. Let me know if you need tests or anything, I've been using my forked version for a few hours and it works great.

### CODE REVIEW

**Review by reowens — APPROVED** [review]
Yes, please!

**Review by reowens — CHANGES_REQUESTED** [review]
I know I approved the changes but when I restarted my Homebridge, the switch and the dimmer separated as two toggles on the device.
IMG_1582
.

**Comment by brandonb927** [comment]
@reowens I actually noticed this as well... the on/off doesn't seem to work as well, which I hadn't tested yet when I made my initial PR.

**Comment by ninjas28** [comment]
Just BTW @reowens and @brandonb927 if you didn't figure it out I think the duplicate is caused by the plugin caching previously set up accessories, so if you had the plugin set up with the dimmer as a dumb switch and then upgraded to this it will keep that accessory and add a duplicate. If you delete the plugin and reinstall this version it only shows the dimmer switch.

**Comment by brandonb927** [comment]
@ninjas28 I tested your theory and I think you're right: I cleared the cached accessory, disabled the plugin, installed my fork, and then let Homebridge discover the Leviton devices and it no-longer shows as two devices in one.

image

**Pull request merged**
